define({
	root: ({
		"_widgetLabel": "Station Locator",
		"routeId": "Route ID",
		"toRouteId": "To Route ID",
		"fromMeasure": "From Station",
		"toMeasure": "To Station",
		"engineering": "Engineering",
		"measureType": "Measure Type",
		"cummulitive": "Continuous",
		"milepost": "Milepost",
		"locate": "Calculate",
		"geometryToMeasure": "Find Station",
		"measureToGeometry": "Find Pipeline",
		"primaryPlaceholder": "2000",
		"fromStationValue": 0,
		"toStationValue": 1000,
		"convertGeometryToMeasure": "Convert geometry to station",
		"clickRoute": "Click on route or enter X,Y coordinates",
		"xy": "Enter X,Y coordinates",
		"measure": "Calculate",
		"missingXY": "Enter X,Y coordinates to get station",
		"dnd": "Drag-Drop Points",
		"dndCaption": "Add file to plot by Lat-Long or Line Station",
		"geoLocation": "Lat, Long",
		"measureRoute": "Line, Station",
		"multiplePipes": "Multiple Lines located",
		"pipeLocated": "Line located",
		"noPipes": "No Line located",
		"lineName": "Pipeline Name",
		"fromEngStation": "From Eng.Station",
		"toEngStation": "To Eng.Station",
		"fromCumStation": "From Cont.Station",
		"toCumStation": "To Cont.Station",
		"noRoutes": "No Line located.",
		"xHint": "Lat(33.111111)",
		"yHint": "Long(-84.111111)",
		"xHint1": "Y (Lat.)",
		"yHint1": "X (Long.)",
		"clear": "Clear",
		"export": "Export",
		"actions": "Actions",
		"addField": "Add Location",
		"undo": "Undo",
		"redo": "Redo",
		"routeIdAndlineNameFieldsNotFound": "RouteId or LineName fields not found",
		"fileFormatNotSupported": "Unsupported file format",
		"fileNotProcessed": "Error fetching items from file",
		"fileMissingFields": "Processing Error!\nCheck data and missing fields.",
		"invalidStationing": "Invalid Station value",
		"invalidLatitudeValue": "Invalid Latitude Value",
		"invalidLongitudeValue": "Invalid Longitude Value",
		"noResult": "No result found for Location ",
		"singleResult": "One result found for Location ",
		"multipleResult": "Multiple results found for Location ",
		"distanceLabel": "Distance : ",
		"mileageLabel": "Mileage : ",
		"notApplicableValue": "Not Applicable",
		"lineNameLabel": "Line Name : ",
		"latitudeLabel": "Latitude : ",
		"longitudeLabel": "Longitude : ",
		"fromLatLongLabel": "From Lat-Long : ",
		"toLatLongLabel": "To Lat-Long : ",
		"engineeringStationLabel": "Engineering Station : ",
		"continuousStationLabel": "Continuous Station : ",
		"milePostLabel": "Milepost : ",
		"resultLabel": "Result ",
		"fromMilePostLabel": " From Milepost : ",
		"fromContinuousStationLabel": "From Cont.Station : ",
		"toContinuousStationLabel": "To Cont.Station : ",
		"toMilePostLabel": " To Milepost : ",
		"fromEngineeringStationLabel": "From Eng.Station : ",
		"toEngineeringStationLabel": "To Eng.Station : ",
		"routeLocation": "Route Location",
		addFromFile: {
			intro: "You can drop or browse for one the following file types:",
			types: {
				"Shapefile": "A Shapefile (.zip, ZIP archive containing all shapefile files)",
				"CSV": "A CSV File (.csv, with address or latitude, longitude and comma, semi-colon or tab delimited)",
				"KML": "A KML File (.kml)",
				"GPX": "A GPX File (.gpx, GPS Exchange Format)",
				"GeoJSON": "A GeoJSON File (.geo.json or .geojson)"
			},
			generalizeOn: "Generalize features for web display",
			dropOrBrowse: "Drop or Browse",
			browse: "Browse",
			invalidType: "This file type is not supported.",
			addingPattern: "{filename}: adding...",
			addFailedPattern: "{filename}: add failed",
			featureCountPattern: "{filename}: {count} feature(s)",
			invalidTypePattern: "{filename}: this type is not supported",
			maxFeaturesAllowedPattern: "A maximum of {count} features is allowed",
			layerNamePattern: "{filename} - {name}",
			generalIssue: "There was an issue.",
			kmlProjectionMismatch: "The spatial reference of the map and KML layer do not match, and the conversion cannot be done on the client."
		},

	})
});
